package org.gcube.application.aquamaps.stubs.dataModel.fields;

public enum HCAF_SFields {

	CSquareCode   ,
	LOICZID       ,
	NLimit        ,
	SLimit        ,
	WLimit        ,
	ELimit        ,
	CenterLat     ,
	CenterLong    ,
	CellArea      ,
	OceanArea     ,
	CellType      ,
	PWater        ,
	FAOAreaM      ,
	FAOAreaIn     ,
	CountryMain   ,
	CountrySecond ,
	CountryThird  ,
	EEZFirst      ,
	EEZSecond     ,
	EEZThird      ,
	EEZAll        ,
	EEZRemark     ,
	LME           ,
	OceanBasin    ,
	Longhurst     ,
	IslandsNo     ,
	Area0_20      ,
	Area20_40     ,
	Area40_60     ,
	Area60_80     ,
	Area80_100    ,
	AreaBelow100  ,
	ElevationMin  ,
	ElevationMax  ,
	ElevationMean ,
	ElevationSD   ,
	WaveHeight    ,
	TidalRange    ,
	LandDist      ,
	Shelf        ,
	Slope       ,
	Abyssal    ,
	Coral     ,
	Estuary  ,
	Seagrass,
	Seamount,
	

	
	
}
