<?xml version="1.0" encoding="UTF-8"?>
<definitions name="AquaMapsTypes"
    targetNamespace="http://gcube-system.org/namespaces/application/aquamaps/types"
    xmlns:tns="http://gcube-system.org/namespaces/application/aquamaps/types"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
    
<!--============================================================

                      T Y P E S
                      
  ============================================================-->
<types>
<xs:schema 
   targetNamespace="http://gcube-system.org/namespaces/application/aquamaps/types"
   xmlns:xs="http://www.w3.org/2001/XMLSchema"
   xmlns:tns="http://gcube-system.org/namespaces/application/aquamaps/types">
<xs:import namespace="http://gcube-system.org/namespaces/common/core/types" 
			schemaLocation="../gcube/common/core/types/GCUBETypes.wsdl" />
<xs:import namespace="http://gcube-system.org/namespaces/common/gis/types"
			schemaLocation="../GISTypes.wsdl" />
 	<xs:include schemaLocation="AquaMapsTypes.xsd" />
 	

</xs:schema>
</types>

</definitions>